/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as LeaderboardRouteImport } from './routes/leaderboard'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DevAddressRouteImport } from './routes/dev.$address'
import { Route as ApiPublicAuthXStartRouteImport } from './routes/api/public/auth/x.start'
import { Route as ApiPublicAuthXCallbackRouteImport } from './routes/api/public/auth/x.callback'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const LeaderboardRoute = LeaderboardRouteImport.update({
  id: '/leaderboard',
  path: '/leaderboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DevAddressRoute = DevAddressRouteImport.update({
  id: '/dev/$address',
  path: '/dev/$address',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicAuthXStartRoute = ApiPublicAuthXStartRouteImport.update({
  id: '/api/public/auth/x/start',
  path: '/api/public/auth/x/start',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicAuthXCallbackRoute = ApiPublicAuthXCallbackRouteImport.update({
  id: '/api/public/auth/x/callback',
  path: '/api/public/auth/x/callback',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/leaderboard': typeof LeaderboardRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/dev/$address': typeof DevAddressRoute
  '/api/public/auth/x/callback': typeof ApiPublicAuthXCallbackRoute
  '/api/public/auth/x/start': typeof ApiPublicAuthXStartRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/leaderboard': typeof LeaderboardRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/dev/$address': typeof DevAddressRoute
  '/api/public/auth/x/callback': typeof ApiPublicAuthXCallbackRoute
  '/api/public/auth/x/start': typeof ApiPublicAuthXStartRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/leaderboard': typeof LeaderboardRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/dev/$address': typeof DevAddressRoute
  '/api/public/auth/x/callback': typeof ApiPublicAuthXCallbackRoute
  '/api/public/auth/x/start': typeof ApiPublicAuthXStartRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/auth'
    | '/leaderboard'
    | '/sitemap.xml'
    | '/dev/$address'
    | '/api/public/auth/x/callback'
    | '/api/public/auth/x/start'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/auth'
    | '/leaderboard'
    | '/sitemap.xml'
    | '/dev/$address'
    | '/api/public/auth/x/callback'
    | '/api/public/auth/x/start'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/auth'
    | '/leaderboard'
    | '/sitemap.xml'
    | '/dev/$address'
    | '/api/public/auth/x/callback'
    | '/api/public/auth/x/start'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AuthRoute: typeof AuthRoute
  LeaderboardRoute: typeof LeaderboardRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  DevAddressRoute: typeof DevAddressRoute
  ApiPublicAuthXCallbackRoute: typeof ApiPublicAuthXCallbackRoute
  ApiPublicAuthXStartRoute: typeof ApiPublicAuthXStartRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leaderboard': {
      id: '/leaderboard'
      path: '/leaderboard'
      fullPath: '/leaderboard'
      preLoaderRoute: typeof LeaderboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dev/$address': {
      id: '/dev/$address'
      path: '/dev/$address'
      fullPath: '/dev/$address'
      preLoaderRoute: typeof DevAddressRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/auth/x/start': {
      id: '/api/public/auth/x/start'
      path: '/api/public/auth/x/start'
      fullPath: '/api/public/auth/x/start'
      preLoaderRoute: typeof ApiPublicAuthXStartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/auth/x/callback': {
      id: '/api/public/auth/x/callback'
      path: '/api/public/auth/x/callback'
      fullPath: '/api/public/auth/x/callback'
      preLoaderRoute: typeof ApiPublicAuthXCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AuthRoute: AuthRoute,
  LeaderboardRoute: LeaderboardRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  DevAddressRoute: DevAddressRoute,
  ApiPublicAuthXCallbackRoute: ApiPublicAuthXCallbackRoute,
  ApiPublicAuthXStartRoute: ApiPublicAuthXStartRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
